# Generated by Django 2.2.4 on 2019-11-21 04:44

from django.db import migrations

import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_possible_number(parsed_phone_number):
            flat.owner_phone_pure = phonenumbers.parse(
                flat.owners_phonenumber, 'RU'
            )
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_phone_pure = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers, move_backward)
    ]
