# Generated by Django 2.2.5 on 2019-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191125_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(db_index=True, related_name='posts', to='blog.Tag', verbose_name='Теги'),
        ),
    ]
